<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $declaration['title'] }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #222; line-height: 1.55; }
        h1 { font-size: 18px; margin: 0 0 8px; color: #1a1a1a; }
        h2 { font-size: 14px; margin: 18px 0 8px; color: #333; }
        p { margin: 0 0 10px; }
        ul { margin: 0 0 10px; padding-left: 18px; }
        li { margin-bottom: 4px; }
        .meta { margin-bottom: 20px; padding: 12px; background: #f5f5f5; border-radius: 4px; }
        .meta p { margin: 0 0 4px; }
        .acceptance { margin-top: 18px; font-weight: bold; }
        .footer { margin-top: 24px; font-size: 10px; color: #666; border-top: 1px solid #ddd; padding-top: 10px; }
    </style>
</head>
<body>
    <h1>{{ $declaration['title'] }}</h1>

    <div class="meta">
        <p><strong>Booking reference:</strong> {{ $order->reference }}</p>
        <p><strong>Participant:</strong> {{ $order->user?->name ?? 'Guest' }}</p>
        <p><strong>Email:</strong> {{ $order->user?->email ?? '—' }}</p>
        <p><strong>Tour:</strong> {{ $order->tour?->title ?? '—' }}</p>
        <p><strong>Travel date:</strong> {{ $order->travel_date?->format('d M Y') ?? '—' }}</p>
        <p><strong>Travelers:</strong> {{ $order->travelers }}</p>
        <p><strong>Accepted on:</strong> {{ $order->declaration_accepted_at?->format('d M Y, h:i A') ?? now()->format('d M Y, h:i A') }}</p>
    </div>

    <h2>Trek Declaration</h2>
    @foreach (preg_split('/\n\s*\n/', trim($declaration['declaration'])) as $paragraph)
        <p>{{ $paragraph }}</p>
    @endforeach

    <h2>{{ $declaration['green_pledge_title'] }}</h2>
    <p>I pledge to:</p>
    <ul>
        @foreach ($declaration['green_pledge_items'] as $item)
            <li>{{ $item }}</li>
        @endforeach
    </ul>

    <p class="acceptance">{{ $declaration['acceptance'] }}</p>

    <div class="footer">
        Generated by {{ config('app.name') }} — {{ now()->format('d M Y') }}
    </div>
</body>
</html>
